
# Generated by Django 5.2.7 on 2025-11-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vc_type', models.CharField(max_length=200, verbose_name='VC Tpre')),
                ('subject_id', models.CharField(max_length=200, verbose_name='Subject ID')),
                ('organization_identity', models.CharField(max_length=200, verbose_name='Organization Identity')),
                ('preauth_code', models.CharField(max_length=200, verbose_name='Preauth code')),
                ('preauth_code_expires_in', models.DateTimeField(verbose_name='Preauth code expiry time')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('creation_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Update time')),
                ('token_data', models.JSONField(blank=True, null=True, verbose_name='Token data')),
                ('tmf_claims', models.JSONField(blank=True, null=True, verbose_name='TMF Claims')),
                ('credential_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Credential ID')),
                ('credential_data', models.JSONField(blank=True, null=True, verbose_name='Credential data')),
            ],
            options={
                'verbose_name': 'Issued Credential',
                'verbose_name_plural': 'Issued Credentials',
            },
        ),
    ]
