# Generated by Django 5.2.7 on 2025-12-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedcredential',
            name='credential_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Credential type'),
        ),
        migrations.AddField(
            model_name='issuedcredential',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Employee ID'),
        ),
    ]
