# Copyright (c) 2025 Comunidad de Madrid & Alastria
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at
# [http://www.apache.org/licenses/LICENSE-2.0](http://www.apache.org/licenses/LICENSE-2.0 "http://www.apache.org/licenses/license-2.0")
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.2.7 on 2025-12-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedcredential',
            name='credential_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Credential type'),
        ),
        migrations.AddField(
            model_name='issuedcredential',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Employee ID'),
        ),
    ]
