
"""
Django settings for punta_cana_back project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from typing import Any, Dict, List
from uuid import uuid4

import environ
import sentry_sdk
from django.utils.translation import gettext_lazy as _


def readEnvBool(envVarName: str, default: bool) -> bool:
    return (os.environ.get(envVarName) in [True, "true", "TRUE", "True", "1", "t", "T"]) or default


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SITE_NAME = os.environ.get("SITE_NAME", "identfy-third-party")
LOCALE_PATHS = [(os.path.join(BASE_DIR, "locale/"))]

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")  # loads .env into os.environ


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.environ.get("DEBUG", 1))


LOG_LEVEL = "DEBUG" if DEBUG else "INFO"
LOG_JSON = env.bool("LOG_JSON", default=True)

DEFAULT_ORG = {
    "NAME": os.environ.get("DEFAULT_ORG_NAME", "Default Org"),
}

# Set default languaje
LANGUAGES = [("es", _("Español"))]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-e&q@0vqsgl27&#h@8pa@dips7x+@jt+k+mrlwg=84mf31on7be",
)


DJANGO_ENVIRONMENT = os.environ.get("DJANGO_ENVIRONMENT", "local")

ALLOWED_HOSTS: List[str] = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

CSRF_TRUSTED_ORIGINS: List[str] = os.environ.get("CSRF_TRUSTED_ORIGINS", "http://localhost,http://127.0.0.1").split(",")


# Base url to serve media files
MEDIA_URL = ".cache/"
# Path where media is stored
MEDIA_ROOT = os.path.join(BASE_DIR, ".cache/")

SERVER_NAME = os.environ.get("DJANGO_ENVIRONMENT", "localhost")

USE_PORT = True if SERVER_NAME == "localhost" else False

USE_HTTPS = int(os.environ.get("USE_HTTPS", False))

SERVER_PORT = os.environ.get("SERVER_PORT", "8000")
if USE_HTTPS:
    SERVER_PORT = "443"

# Application definition

INSTALLED_APPS = [
    "daphne",
    # Django theme -> It must be the first
    "jazzmin",
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "corsheaders",
    "django_apscheduler",
    "django_celery_results",
    "django_filters",
    "django_rest_passwordreset",
    "drf_yasg",
    "django_jsonform",
    "rest_framework",
    "rest_framework.authtoken",
    "django_prometheus",
    "django_json_widget",
    # Own apps
    "tasks_protocol.apps.TasksProtocolConfig",
    "project_commands",
    "tasks",
    "user",
    "web_resources",
    "templatetags",
    "issuance",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "project.logging.middleware.request_id_middleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

# Connection with Frontend
FRONTEND_URL = os.environ.get("FRONTEND_URL", None)

CORS_ORIGIN_ALLOW_ALL: bool = readEnvBool("CORS_ORIGIN_ALLOW_ALL", False)
CORS_ALLOWED_ORIGINS: List[str] = os.environ.get(
    "CORS_ALLOWED_ORIGINS", "http://localhost:8000,http://localhost:3000"
).split(",")
DJANGO_REST_PASSWORDRESET_NO_INFORMATION_LEAKAGE: bool = True

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "libraries": {
                "custom_extras": "templatetags.custom_extras",
            },
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_prometheus.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "postgres"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "postgres"),
        "HOST": os.environ.get("DB_HOST", "postgres"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}

database_url = os.environ.get("DATABASE_URL", None)

if database_url:
    import dj_database_url

    DATABASES["default"] = dj_database_url.parse(database_url)


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "es-es"

TIME_ZONE = "Europe/Madrid"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = "static"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATICFILES_DIRS = [
    BASE_DIR / "styles",
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CELERY_BROKER_URL = os.environ.get("REDIS_URL", "redis://redis:6379/0")

# Email settings
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.serviciodecorreo.es")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 465))
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "no-reply@redisbe.com")
DEFAULT_FROM_EMAIL = os.environ.get("SERVER_EMAIL", "no-reply@redisbe.com")
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_BACKEND = "postmarker.django.EmailBackend"
#    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


JAZZMIN_SETTINGS: Dict[str, Any] = {
    "site_title": "Credential Issuer Admin",
    "site_header": "Credential Issuer",
    "site_brand": "Credential Issuer",
    "login_logo": "images/logo/logo.png",
    "login_logo_dark": "images/logo/logo.png",
    "site_logo_classes": "img-circle",
    "site_icon": "images/icon/logo.ico",
    "welcome_sign": _("Welcome to the ISBE Credential Issuer Admin Site"),
    "copyright": _("Alastria"),
    "search_model": ["auth.User", "auth.Group"],
    "user_avatar": None,
    ############
    # Top Menu #
    ############
    "topmenu_links": [
        {
            "name": "Home",
            "url": "admin:index",
            "permissions": ["auth.view_user"],
        },
        {
            "name": "Support",
            "url": "https://github.com/farridav/django-jazzmin/issues",
            "new_window": True,
            "icon": "far fa-question-circle",
        },
        {"model": "auth.User"},
    ],
    #############
    # User Menu #
    #############
    "usermenu_links": [
        {
            "name": "Support",
            "url": "https://github.com/farridav/django-jazzmin/issues",
            "new_window": True,
            "icon": "far fa-question-circle",
        },
        {"model": "auth.user"},
    ],
    #############
    # Side Menu #
    #############
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "authtoken.tokenproxy": "fas fa-magic",
        "django_celery_results.groupresult": "far fa-object-group",
        "django_celery_results.taskresult": "fas fa-tasks",
        "django_rest_passwordreset.resetpasswordtoken": "fas fa-exchange-alt",
        "organizations.node": "fab fa-linode",
        "organizations.network": "fas fa-network-wired",
        "organizations.contract": "fas fa-file-contract",
        "organizations.organization": "fas fa-building",
        "organizations.organizationdid": "fas fa-id-card",
        "organizations.organizationkeys": "fas fa-key",
        "organizations.entity": "fas fa-user-lock",
        "openid.verifiermetadata": "fas fa-database",
        "openid.presentationdefinition": "fas fa-book",
        "openid.issuanceflow": "fas fa-edit",
        "openid.verifyflow": "fas fa-envelope-open",
        "openid.noncemanager": "fas fa-random",
        "did_management.didmatch": "fas fa-equals",
        "credentials.verifiablecredential": "fas fa-id-card-alt",
        "credentials.issuedverifiablecredential": "fas fa-folder",
        "ebsi.accreditationtoattest": "fas fa-address-card",
        "ebsi.accreditationtoaccredit": "fas fa-file-signature",
        "ebsi.accreditationtoonboard": "fas fa-user-plus",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    #################
    # Related Modal #
    #################
    "related_modal_active": False,
    #############
    # UI Tweaks #
    #############
    "custom_css": "css/issuer.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    ###############
    # Change view #
    ###############
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
        "organizations.organization": "vertical_tabs",
    },
    "language_chooser": False,
    "custom_links": {
        "credentials": [
            {
                "name": "Self Issuance",
                "url": "/admin/self-issuance/",
                "icon": "fas fa-file-signature",
                "permissions": ["auth.self_assertion"],
            },
            {
                "name": "Request VC",
                "url": "/admin/request-vc/",
                "icon": "fas fa-id-badge",
                "permissions": ["auth.request_vc"],
            },
        ]
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "minty",
    "dark_mode_theme": "superhero",
}

if not DEBUG:
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(
        dsn=os.environ.get("SENTRY_DSN", ""),
        environment=DJANGO_ENVIRONMENT,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            RedisIntegration(),
        ],
        traces_sample_rate=1.0,
        send_default_pii=True,
    )


SIMPLE_JWT = {
    "TOKEN_OBTAIN_SERIALIZER": "user.serializers.CustomTokenLoginSerializer",
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.environ.get("ACCESS_TOKEN_LIFETIME", 15))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.environ.get("REFRESH_TOKEN_LIFETIME", 1))),
}


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_REDIRECT_URL = ""

LOGIN_URL = "/"

ASGI_APPLICATION = "project.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}  # TODO USE REDIS ?
INTERNAL_IPS = ["*"]

WS_FEATURE_TOGGLE_PATH = os.environ.get("WS_FEATURE_TOGGLE_PATH", "ws://localhost:8000/ws/features/updates")

BACKEND_NOTIFICATIONS_SECRET = os.environ.get("BACKEND_NOTIFICATIONS_SECRET", str(uuid4()))


CELERY_RESULT_BACKEND = "django-db"
CELERY_RESULT_EXTENDED = True

# OUR VARS
BACKEND_DOMAIN = os.environ.get("BACKEND_DOMAIN", "http://localhost:8000")
NETWORK_SERVICE_HOST = os.environ.get("NETWORK_SERVICE_HOST", "")
VALIDA_ONE = os.environ.get("VALIDA_ONE", "http://valida.one")
CERTIFICATIONS_SERVICE_PATH = os.environ.get("CERTIFICATIONS_SERVICE_PATH", "")

TOKENIZATION_SERVICE = os.environ.get("TOKENIZATION_SERVICE", "")
TOKENIZATION_ACCOUNT_MNEMONIC = os.environ.get(
    "TOKENIZATION_ACCOUNT_MNEMONIC",
    "",
)
TOKENIZATION_ACCOUNT_PATH = os.environ.get(
    "TOKENIZATION_ACCOUNT_PATH",
    "",
)

IPFS_GATEWAY = os.environ.get("IPFS_GATEWAY", "https://gateway.pinata.cloud/ipfs/")
ALASTRIA_BLOCK_EXPLORER = os.environ.get(
    "ALASTRIA_BLOCK_EXPLORER",
    "https://blkexplorer1.telsius.alastria.io/transaction/",
)

# AWS CONNECTION
AWS_ACCESS_KEY = os.environ.get("AWS_ACCESS_KEY", "")
AWS_SECRET_KEY = os.environ.get("AWS_SECRET_KEY", "")
AWS_BUCKET = os.environ.get("AWS_BUCKET", "")
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "eu-central-1")

# APP LINKS
ANDROID_APP_LINK = os.environ.get("ANDROID_APP_LINK", "")
IOS_APP_LINK = os.environ.get("IOS_APP_LINK", "")
WEB_APP_LINK = os.environ.get("FRONTEND_URL", "")


JWT_PASSWORD = os.environ.get("JWT_PASSWORD", "24c@lgo")


LOGOUT_REDIRECT_URL = "/"

OPERATOR_AUTOMATIC_STAFF = os.environ.get("OPERATOR_AUTOMATIC_STAFF", True)
CRYPTO_SERVICE_URL = os.environ.get("CRYPTO_SERVICE_URL", "")

GOOGLE_TAG_ACTIVE = int(os.environ.get("GOOGLE_TAG_ACTIVE", 0))  # Active only production deploy
GOOGLE_TAG_KEY = os.environ.get("GOOGLE_TAG_KEY", "GTM-XXXXX")  # Set correct value for OOGLE_TAG_KEY

LOGGING = {
    "version": 1,
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        }
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            #    "level": "DEBUG", # debug show SQL queries
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
        }
    },
    "loggers": {
        # Active for show SQL queries
        #        "django.db.backends": {
        #            "level": "DEBUG",
        #            "handlers": ["console"],
        #            "propagate": False,
        #        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}


# REST_FRAMEWORK = {
#     "DEFAULT_AUTHENTICATION_CLASSES": [
#         "rest_framework.authentication.BasicAuthentication",
#         "rest_framework.authentication.SessionAuthentication",
#         "rest_framework_simplejwt.authentication.JWTAuthentication,",
#     ],
#     "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
# }

# REST_FRAMEWORK = {
#     "DEFAULT_PARSER_CLASSES": [
#         "rest_framework.parsers.MultiPartParser",
#         "rest_framework.parsers.JSONParser",
#     ]
# }


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": [],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
    ],
}


SWAGGER_SETTINGS = {
    "USE_SESSION_AUTH": False,
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Paste: Bearer <your_jwt_here>",
        }
    },
}


# TODO pendiente de ver si será la misma url base de IDENTFY_CONNECTOR_API_URL
KEYCLOAK_JWKS_URL = os.getenv("KEYCLOAK_JWKS_URL")
IDENTFY_CONNECTOR_API_URL = os.getenv("IDENTFY_CONNECTOR_API_URL", "")
IDENTFY_CONNECTOR_API_KEY = os.getenv("IDENTFY_CONNECTOR_API_KEY", "")
TMF_API_URL = os.getenv("TMF_API_URL", "")

PROMETHEUS_METRIC_NAMESPACE = os.environ.get("PROMETHEUS_METRIC_NAMESPACE", "")


try:
    from .settings_local import *
except ImportError:
    pass
