replicaCount: 1

fullnameOverride: "${APP_NAME}"

image:
  repository: ${ECR_REGISTRY}/${ECR_REPOSITORY} # Reemplaza con tu imagen de Docker
  pullPolicy: Always
  tag: ${IMAGE_TAG} # Reemplaza con el tag de tu imagen

secrets:
  # Agrega aquí tus secretos en formato clave: valor
  SECRET_KEY: ${SECRET_KEY}
  DATABASE_URL: ${DATABASE_URL}
  EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
  IDENTFY_CONNECTOR_API_KEY: ${IDENTFY_CONNECTOR_API_KEY}

app:
  port: 8000
  envs:
    ALLOWED_HOSTS: "${ALLOWED_HOSTS}"
    BACKEND_DOMAIN: "${BACKEND_DOMAIN}"
    CSRF_TRUSTED_ORIGINS: "${CSRF_TRUSTED_ORIGINS}"
    CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}"
    IDENTFY_CONNECTOR_API_URL: "${IDENTFY_CONNECTOR_API_URL}"
    TMF_API_URL: "${TMF_API_URL}"
    KEYCLOAK_JWKS_URL: "${KEYCLOAK_JWKS_URL}"

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

service:
  type: ClusterIP
  port: 8000
  # Puerto donde tu aplicación expone las métricas de Prometheus
  metricsPort: 8000

# Configuración del Ingress (ALB)
ingress:
  enabled: true
  # Reemplaza con el hostname deseado
  hostname: ${HOST_NAME}
  # Anotaciones clave para el AWS Load Balancer Controller
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # Al usar group.name, los tags deben de ser iguales.
    alb.ingress.kubernetes.io/tags: Application=isbe-apps
    # Opcional: Para usar un certificado ACM existente
    alb.ingress.kubernetes.io/certificate-arn: ${ARN_CERT}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    #alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-Res-2021-06
    # Al usar group.name, todas las reglas con el mismo nombre de grupo se agrupan en un solo ALB
    alb.ingress.kubernetes.io/group.name: isbe-apps

# Integraciones de la plataforma
observability:
  enabled: true # Activa la creación del ServiceMonitor y PrometheusRule
  dashboard:
    # NO ACTIVAR. Usaremos otra configuración global para disponer de un único dashboard con varios paneles
    enabled: false # Activa la creación del Dashboard de Grafana 
